### ISSUE TITLE
Request for Assistance: Code Implementation for Calculation and Plotting of ECE/ENCE Curves in Fig4 and Fig5 of the Paper

### ISSUE THREAD

**Issue by magnificent0121** [chuiyang/atom-based_uncertainty_model#1]
Thanks to the authors for your outstanding work. I am a beginner in the field of deep learning related to uncertainty analysis, and I am interested in the calculation of ece/ence and the plotting of the curves in Fig4 and Fig5 of this paper of yours, but unfortunately I don't seem to find a counterpart in the code, could you please shed more light on this?

**Comment by chuiyang** [comment]
Hi, thanks for commenting!
I have pushed a file to calculate the x-y values on both error-based and confidence-based calibration plots at [utils/uncertainty_metrics.py](https://github.com/chuiyang/atom-based_uncertainty_model/blob/main/utils/uncertainty_metrics.py)

After getting the x-y values of the plot with these functions, you should be able to plot the curves and calculate the ECE/ENCE values by averaging the differences between the x-y values.
Wish you all the best and enjoy exploring UQ!
